name: firebase_messaging
description: Flutter plugin for Firebase Cloud Messaging, a cross-platform
  messaging solution that lets you reliably deliver messages on Android and iOS.
homepage: https://firebase.flutter.dev/docs/messaging/overview
repository: https://github.com/FirebaseExtended/flutterfire/tree/master/packages/firebase_messaging/firebase_messaging
version: 10.0.4

environment:
  sdk: '>=2.12.0 <3.0.0'
#  flutter: ">=1.12.13+hotfix.5"

dependencies:
  firebase_core: ^1.19.2
  firebase_core_platform_interface: ^4.4.3
  firebase_messaging_platform_interface: ^4.0.0
  firebase_messaging_web: ^3.0.0
  flutter:
    sdk: flutter
  meta: ^1.7.0

dev_dependencies:
  async: ^2.8.2
  flutter_test:
    sdk: flutter
  mockito: ^5.2.0
  plugin_platform_interface: ^2.1.2
  test: any

flutter:
  plugin:
    platforms:
      android:
        package: io.flutter.plugins.firebase.messaging
        pluginClass: FlutterFirebaseMessagingPlugin
      ios:
        pluginClass: FLTFirebaseMessagingPlugin
      macos:
        pluginClass: FLTFirebaseMessagingPlugin
      web:
        default_package: firebase_messaging_web
